env:
  node: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
rules:
  indent: [2, 4]
  object-curly-spacing: [1, always]
  array-bracket-spacing: [1, always]
  max-len: [2, 119]
  require-jsdoc: [0]
